### ISSUE TITLE
gemfile needed to run

### ISSUE THREAD

**Issue by adnjoo** [opieters/jekyll-gallery-example#2]
what should I put in the gemfile?

**Comment by tjan90** [comment]
It doesn't need gemfile, as there are no dependencies required to run this site. Just clone the repo and give the command "jekyll serve".

**Comment by tjan90** [comment]
> what should I put in the gemfile?

It doesn't need gemfile, as there are no dependencies required to run this site. Just clone the repo and give the command "jekyll serve".
