### ISSUE TITLE
HTTP Strict Transport Security policy

### ISSUE THREAD

**Issue by jazzyjackson** [opieters/jekyll-gallery-example#3]
I'm unable to load the blog at https://www.olivierpieters.be/blog/2016/02/26/creating-a-jekyll-image-gallery.html

Firefox (and Safari) prevents the page from loading with the message:

> "Did Not Connect: Potential Security Issue
> ...
> www.olivierpieters.be has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.
> 
> The issue is most likely with the website, and there is nothing you can do to resolve it. You can notify the website’s administrator about the problem."

My version of firefox directs me to this page to 'learn more': https://support.mozilla.org/en-US/kb/secure-connection-failed-firefox-did-not-connect

Perhaps it's just a matter of updating your certificates or allowing unsecure conections?

Thanks, your Jekyll code looks very useful to me!

**Comment by opieters** [comment]
This is indeed an issue, I will fix it this week. If you remove the www. from the URL, the link should work. The issue is that I forgot to re-enable the redirect from www. to the URL without www. Thanks for pointing this out to me.

**Comment by opieters** [comment]
Should be fixed now. Thank you for the feedback!
