### ISSUE TITLE
I am very interested in your combination Isotope / LightGallery - does it allow easy sorting?

### ISSUE THREAD

**Issue by 888ba8** [opieters/jekyll-gallery-example#5]
Hi @opieters I am currently using another LightGallery plug-in https://jimmyxiao.me/guides/technical/2019/07/28/folder-based-jekyll-lightgallery which however does not feature Isotope.

I am looking for a sorting solution so this got me interested in your plug-in. I understand Isotope allows for filtering/sorting?

Does it allow for a way to e.g. reverse the order of the images, e.g. Z->A instad of A->Z? Many thanks in advance.

**Comment by opieters** [comment]
Sorting is possible with Isotope if you include the necessary attributes in the HTML code. You should have a look at the Isotope documentation: https://isotope.metafizzy.co/
